@startuml
title 1234Altwagen - Class Diagram


class CarManager {
    -cars: Car[]
}

class Car {
    -chassisNumber: string
    -price: float
    -constructionYear: int
    -drivenKM: int
    -brand: string
    -model: string
    -note: string
    -location: Location
    -status: CAR_STATUS
    +Car(float, String, int, String, String, String, Location, CAR_STATUS)
}

class Location {
    -address: Address
    -name: string
    -maxCars: int
    -carCount: int
    +Location(Address, String, int, int)
}

class RequestManager {
    -requests: Request[]
}

class Request {
    -car: Car
    -employee: Employee
    -customer: Customer
    -type: REQUEST_TYPE
    -status: REQUEST_STATUS
    +Request(REQUEST_TYPE, Car, Customer)
}

class Address {
    -country: string
    -city: string
    -zip: string
    -street: string
    -houseNumber: string
    +Address(int, String, String, String, String, String, String)
}

class Controller {
    +getAllCars(): Car[]
    +getCarsByStatus(CAR_STATUS): Car[]
    +deleteUser (int userId): boolean
    +registerCustomer (String, String, String, String, String, String, String, String, String): User
    +registerEmployee (String, String, String, String, String, String, String, String, String): User
    -registerUser(User, boolean)
}

class UserManager {
    -customers: Customer[]
    -employees: Employee[]
}

class User {
    ~userId: int
    ~firstname: string
    ~lastname: string
    ~eMail: string
    ~password: string
    ~userAddress: Address
}
class Customer {
    -requestCount: int
    +requestSellCar(Car): Request
    +requestBuyCar(Car): Request
    +cancelRequest(Request): boolean
    +decreaseRequestCount(): void
    -createRequest(Car, REQUEST_TYPE): Request
}
class Employee {
    +sellCar(Car): bool
    +sellCar(Car, float): bool
    +acceptRequest(Request): bool
    +denyRequest(Request): bool
    +listPendingRequests(): Request[]
}

enum CAR_STATUS {
    +forSale
    +notReadyForSale
    +onRequest
}

enum REQUEST_STATUS {
    +pending
    +accepted
    +denied
}

enum REQUEST_TYPE {
    +buy
    +sell
}

Customer --> User
Employee --> User

Car -- CarManager
Request -- RequestManager
Customer -- UserManager
Employee -- UserManager
Car -- Location
Car -- Request
Location -- Address
Request -- Customer
Request -- Employee
Address -- User
Car -- CAR_STATUS
Request -- REQUEST_TYPE
Request -- REQUEST_STATUS
@enduml
